spring.application.name=backend-inventory

spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}

app.security.tenant-id=${AZURE_TENANT_ID:ddfccc4f-6e03-4e1c-90b3-e5ba0d8a9523}
app.security.audiences=${AZURE_API_AUDIENCES:api://0a8285a1-9a6e-4150-9ffc-57c1badf3bff,0a8285a1-9a6e-4150-9ffc-57c1badf3bff}